# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pasword.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(244, 228)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        MainWindow.setFont(font)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        MainWindow.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:0.166 rgba(255, 255, 0, 255), stop:0.333 rgba(0, 255, 0, 255), stop:0.5 rgba(0, 255, 255, 255), stop:0.666 rgba(0, 0, 255, 255), stop:0.833 rgba(255, 0, 255, 255), stop:1 rgba(255, 0, 0, 255))")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(30, 10, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.title.setFont(font)
        self.title.setMouseTracking(False)
        self.title.setStyleSheet("color: red; border: 2px solid black;")
        self.title.setObjectName("title")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(30, 60, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.result.setFont(font)
        self.result.setStyleSheet("color: red; border: 2px solid black;")
        self.result.setObjectName("result")
        self.btn_OK = QtWidgets.QPushButton(self.centralwidget)
        self.btn_OK.setGeometry(QtCore.QRect(60, 160, 111, 23))
        font = QtGui.QFont()
        font.setFamily("Segoe Script")
        self.btn_OK.setFont(font)
        self.btn_OK.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.btn_OK.setStyleSheet("color: blue;\n"
"border: 2px solid black;\n"
"border-radius: 5px;")
        self.btn_OK.setObjectName("btn_OK")
        self.cb_number = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_number.setGeometry(QtCore.QRect(30, 100, 171, 17))
        self.cb_number.setStyleSheet("color: red;\n"
" border: 2px solid black;")
        self.cb_number.setObjectName("cb_number")
        self.cb_alphabet = QtWidgets.QCheckBox(self.centralwidget)
        self.cb_alphabet.setGeometry(QtCore.QRect(30, 120, 191, 17))
        font = QtGui.QFont()
        self.cb_alphabet.setFont(font)
        self.cb_alphabet.setStyleSheet("color: red;\n"
" border: 2px solid black;")
        self.cb_alphabet.setObjectName("cb_alphabet")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 244, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "Генератор паролів"))
        self.result.setText(_translate("MainWindow", "Тут буде результат"))
        self.btn_OK.setText(_translate("MainWindow", "Згенерувати"))
        self.cb_number.setText(_translate("MainWindow", "Використовувати числа"))
        self.cb_alphabet.setText(_translate("MainWindow", "Використовувати алфавіт"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
